# Generated by Django 4.2.1 on 2024-03-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название квартиры')),
                ('price', models.CharField(max_length=6, verbose_name='Цена за ночь')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('numberOfRooms', models.CharField(max_length=4, verbose_name='Номер квартиры')),
                ('typeOfHouse', models.CharField(max_length=200, verbose_name='Тип квартиры')),
                ('countRooms', models.CharField(max_length=2, verbose_name='Тип квартиры')),
                ('description', models.TextField(max_length=500, verbose_name='Описание квартиры')),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Квартиры',
                'verbose_name_plural': 'Квартира',
            },
        ),
    ]
