# Generated by Django 4.2.1 on 2024-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_modelrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrooms',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='modelrooms',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='modelrooms',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
