# Generated by Django 4.2.1 on 2024-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
