# Generated by Django 4.2.1 on 2024-03-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_users_user_img_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
